env:
  browser: true
  es2021: true
  'jest/globals': true
ignorePatterns:
  - bin/**
  - dist/**
  - node_modules/**
  - 'jest.config.js'
extends:
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
plugins:
  - eslint-plugin-import
  - unused-imports
  - '@typescript-eslint'
  - jest
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules:
  quote-props: off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-explicit-any': off
  sort-imports:
    - error
    - { ignoreDeclarationSort: true }
